apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "app-protect-waf-orchestrator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app-protect-waf-orchestrator.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "app-protect-waf-orchestrator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
